export const App_Features = [
  {
    id: "01",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "02",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized and meaningful.",
  },
  {
    id: "03",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "04",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
  {
    id: "05",
    title: "Track Progress and Stay Motivated",
    description:
      "Monitor your preparation journey with progress tracking and motivational milestones to keep you moving forward.",
  },
];
